### ISSUE TITLE
Integration with QSickChill

### ISSUE THREAD

**Issue by dci2112** [VeNoMouS/cloudscraper#15]
This is on a QNAP NAS using the current git master of SickChill. 

I updated the QSickChill/SickChill/sickbeard/helpers.py to replace cfscrape:

```
diff helpers.py.old helpers.py
--- helpers.py.old
+++ helpers.py
@@ -47,7 +47,8 @@
 import adba
 import bencode
 import certifi
-import cfscrape
+#import cfscrape
+import cloudscraper
 import rarfile
 import requests
 import six
@@ -1375,7 +1376,8 @@
 
     session.headers.update({'User-Agent': USER_AGENT, 'Accept-Encoding': 'gzip,deflate'})
 
-    session = cfscrape.create_scraper(sess=session)
+    #session = cfscrape.create_scraper(sess=session)
+    session = cloudscraper.create_scraper(sess=session, interpreter='nodejs')
 
     return CacheControl(sess=session, cache_etags=True)

``` 

Without the interpreter argument, I encountered the below error:

`AA AttributeError: 'module' object has no attribute 'disable_pyimport' 
`

With the interpreter argument we are back to the tuples error:

```
AA TypeError: tuple indices must be integers, not str 
AA return (logger.ERROR, logger.WARNING)[exception.message and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception.message] 
AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/helpers.py", line 1524, in get_level AA logger.log(default.format(error, type(error.__class__.__name__)), get_level(error)) 
AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/helpers.py", line 1580, in handle_requests_exception AA handle_requests_exception(error) 
AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/helpers.py", line 1467, in getURL 
AA return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs) 
AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickchill/providers/GenericProvider.py", line 372, in get_url AA self.get_url(login_url, returns='text') 
AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/providers/iptorrents.py", line 83, in login 
AA if not self.login(): 
AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/providers/iptorrents.py", line 108, in search 
AA items_list += self.search(search_string, ep_obj=episode) 
AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickchill/providers/GenericProvider.py", line 170, in find_search_results AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality) 
AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/search.py", line 474, in searchProviders 
AA Traceback (most recent call last): 2019-05-03 08:22:10 
ERROR SEARCHQUEUE-MANUAL-121361 :: [IPTorrents] :: [b3da866] Exception while searching IPTorrents. Error: TypeError('tuple indices must be integers, not str',) 2019-05-03 08:22:02 
INFO SEARCHQUEUE-MANUAL-121361 :: [IPTorrents] :: Performing episode search for Game of Thrones 2019-05-03 08:21:57 INFO SEARCHQUEUE-MANUAL-121361 :: Beginning manual search for: [Game of Thrones - S08E02 - A Knight of the Seven Kingdoms] 

```

**Comment by VeNoMouS** [comment]
@dci2112 can you please confirm the version of js2py?

**Comment by VeNoMouS** [comment]
hrrm are you sure you using that correctly, `disable_pyimport` is part of the js2py interpreter but your defining `nodejs` are you sure that is all you've changed?!

**Comment by VeNoMouS** [comment]
re ```AA AttributeError: 'module' object has no attribute 'disable_pyimport'` please confirm your js2py version as `disable_pyimport` has been part of it js2py since ~2016...

do you have `nodejs` installed?

**Comment by dci2112** [comment]
I am using the versions packaged with QSickChill to my knowledge...I'm not sure how QSickchill/bin is populated though. 

js2py:

```
[/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin] # pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package           Version 
----------------- --------
asn1crypto        0.24.0  
Brotli            1.0.7   
certifi           2019.3.9
cffi              1.11.5  
chardet           3.0.4   
cloudscraper      1.1.2   
cryptography      2.3.1   
enum34            1.1.6   
idna              2.7     
ipaddress         1.0.22  
Js2Py             0.63    
lxml              4.2.5   
netifaces         0.10.7  
pip               19.1    
pycparser         2.19    
pycrypto          2.6.1   
pycurl            7.43.0.2
pyjsparser        2.7.1   
pyOpenSSL         18.0.0  
pytz              2019.1  
requests          2.21.0  
requests-toolbelt 0.9.1   
setuptools        41.0.1  
six               1.11.0  
tzlocal           1.5.1   
urllib3           1.24.2  
[/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin] # which pip
/share/CACHEDEV1_DATA/.qpkg/QSickChill/bin/pip

```

NodeJs:

```
[/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin] # which node
/usr/bin/node
[/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin] # ls -l node
-rwxrwx--x 1 admin administrators 27311456 2016-10-29 14:20 node*
[/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin] # node --version
v6.9.1

```

**Comment by VeNoMouS** [comment]
Ok looked at the base code for sickchill, it has a REALLY old js2py in its libdir the `evaljs.js` doesn't even contain the function `disable_pyimport`

**Comment by VeNoMouS** [comment]
Also I would test the library outside of sickchill first in regards to the nodejs issue

```python
import cloudscraper
cloudscraper.create_scraper(interpreter='nodejs')
cloudscraper.get('https://www.japscan.to/search/')
```

for example or....

```python
import cloudscraper
cloudscraper.create_scraper(interpreter='nodejs')
print(cloudscraper.get_tokens('https://www.japscan.to/search/'))
```

**Comment by dci2112** [comment]
BTW, thank you for your attention in trying to get this working...SickChill has been broken for me for a long time because of these scrape issues.

Here we go:

```
[~] # cat test_cs.py
import cloudscraper
cloudscraper.create_scraper(interpreter='nodejs')
print(cloudscraper.get_tokens('https://www.japscan.to/search/'))

```

```
[~] # python test_cs.py       
ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.
ERROR:root:"https://www.japscan.to/search/" returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "test_cs.py", line 3, in <module>
    print(cloudscraper.get_tokens('https://www.japscan.to/search/'))
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/cloudscraper/__init__.py", line 259, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/cloudscraper/__init__.py", line 142, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/cloudscraper/__init__.py", line 203, in sendChallengeResponse
    params['jschl_answer'] = JavaScriptInterpreter.dynamicImport(self.interpreter).solveChallenge(body, domain)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/cloudscraper/interpreters/__init__.py", line 81, in solveChallenge
    js
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/cloudscraper/interpreters/js2py.py", line 27, in eval
    result = context.eval('{}{}'.format(jsEnv, js))
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/js2py/evaljs.py", line 190, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/js2py/evaljs.py", line 185, in execute
    exec (compiled, self._context)
  File "<EvalJS snippet>", line 4, in <module>
  File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/js2py/base.py", line 1463, in call
    return Js(self.code(*args))
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/js2py/host/jseval.py", line 45, in Eval
    executor(py_code)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/js2py/host/jseval.py", line 51, in executor
    exec (code, globals())
  File "<string>", line 133, in <module>
  File "<string>", line 132, in PyJs_LONG_37_
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/js2py/base.py", line 1463, in call
    return Js(self.code(*args))
  File "<string>", line 130, in PyJs_anonymous_36_
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/lib/python2.7/site-packages/js2py/base.py", line 994, in callprop
    '%s is not a function' % cand.typeof())
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function

```

It looks like it's still using js2py....not nodejs...

**Comment by VeNoMouS** [comment]
@dci2112 update your cloudscraper, that bug was reported couple hrs ago and has since been fixed ;P CF changed their code ;)

**Comment by dci2112** [comment]
That did it, I am back up and running, thank you!!!

**Comment by VeNoMouS** [comment]
np mate, I'm going to close this off if you don't mind, we can re-open it, if you have further issues.

Enjoy
