### ISSUE TITLE
ImportError: cannot import name CloudflareLoopProtection

### ISSUE THREAD

**Issue by barakagb** [VeNoMouS/cloudscraper#205]
In py 2.7 just importing the cloudscraper results into the below error

Python 2.7
Ubuntu 18.04
cloudscraper v1.2.34

```python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudscraper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python2.7/site-packages/cloudscraper/__init__.py", line 27, in <module>
    from .exceptions import (
ImportError: cannot import name CloudflareLoopProtection
>>> 
```

**Comment by VeNoMouS** [comment]
check you dont have a quite old version of cloudscraper goto `"/home/user/.local/lib/python2.7/site-packages/cloudscraper/` and **make sure you don't** have a `exceptions` directory, if you do, delete it
