### ISSUE TITLE
No module named 'pyparsing'

### ISSUE THREAD

**Issue by Django1211** [VeNoMouS/cloudscraper#215]
Hi, i got some error on CF. 

Output : Unable to parse Cloudflare anti-bots page: No module named 'pyparsing'

but pyparsing is installed on my computer.

I missed something ?

Thanks for your help :)

**Comment by Fran008** [comment]
Are you using Python2 or Python3? Maybe you have installed pyparsing only in one of them.

When you install new version of Cloudscraper it installs only pyparsing for Python3. If you are using Python2 then you have to do the installation of pyparsing manually.

sudo apt-get install python-pyparsing
sudo apt-get install python3-pyparsing

**Comment by VeNoMouS** [comment]
Hrrm.... how did you install cloudscraper?

py2 and py3 in https://pypi.org/project/pyparsing/2.4.7/#files

also its in requirements.txt

https://github.com/VeNoMouS/cloudscraper/blob/master/requirements.txt#L4

as well as 

https://github.com/VeNoMouS/cloudscraper/blob/master/setup.py#L38


so not sure why you're having a problem!?

**Comment by VeNoMouS** [comment]
```bash
root@tvz0r:/tmp# pip2 install cloudscraper
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting cloudscraper
  Using cached cloudscraper-1.2.36-py2.py3-none-any.whl (109 kB)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python2.7/dist-packages (from cloudscraper) (0.9.1)
Collecting pyparsing>=2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Requirement already satisfied: requests>=2.9.2 in /usr/local/lib/python2.7/dist-packages (from cloudscraper) (2.22.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.9.2->cloudscraper) (2019.6.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.9.2->cloudscraper) (1.25.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.9.2->cloudscraper) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.9.2->cloudscraper) (2.8)
Installing collected packages: pyparsing, cloudscraper
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 2.1.10
    Uninstalling pyparsing-2.1.10:
      Successfully uninstalled pyparsing-2.1.10
Successfully installed cloudscraper-1.2.36 pyparsing-2.4.7
root@tvz0r:/tmp#
```

it installs fine via pip for py2

**Comment by Fran008** [comment]
sudo python setup.py install

<pre>byte-compiling build/bdist.linux-x86_64/egg/cloudscraper/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudscraper.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudscraper.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudscraper.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudscraper.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudscraper.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
cloudscraper.user_agent.__init__: module references __file__
creating 'dist/cloudscraper-1.2.36-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing cloudscraper-1.2.36-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/cloudscraper-1.2.36-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/cloudscraper-1.2.36-py2.7.egg
Extracting cloudscraper-1.2.36-py2.7.egg to /usr/local/lib/python2.7/dist-packages
cloudscraper 1.2.36 is already the active version in easy-install.pth
Installed /usr/local/lib/python2.7/dist-packages/cloudscraper-1.2.36-py2.7.egg
Processing dependencies for cloudscraper==1.2.36
Searching for pyparsing>=2.4.7
Reading https://pypi.python.org/simple/pyparsing/
Downloading https://files.pythonhosted.org/packages/4f/49/f5ef814360ce13ab6eab4e05762ce555ed5bbc169ac941229a3355e91
97a/pyparsing-3.0.0a1.tar.gz#sha256=700d17888d441604b0bd51535908dcb297561b040819cccde647a92439db5a2a
Best match: pyparsing 3.0.0a1
Processing pyparsing-3.0.0a1.tar.gz
Writing /tmp/easy_install-HTYsRY/pyparsing-3.0.0a1/setup.cfg
Running pyparsing-3.0.0a1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-HTYsRY/pyparsing-3.0.0a1/egg-dist-tmp-
JqzXBT
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 436, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 680, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 727, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 772, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 699, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 725, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 906, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1145, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1131, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-HTYsRY/pyparsing-3.0.0a1/setup.py", line 10, in <module>
    readme = fp.read()
  File "/tmp/easy_install-HTYsRY/pyparsing-3.0.0a1/pyparsing/__init__.py", line 104, in <module>
  File "/tmp/easy_install-HTYsRY/pyparsing-3.0.0a1/pyparsing/core.py", line 166
    nonlocal found_arity, limit
                       ^
SyntaxError: invalid syntax</pre>

So if I want to execute cloudscraper in python2 I have to install pyparsing manually... and then it works Ok:

sudo apt-get install python-pyparsing

**Comment by Fran008** [comment]
We are not the only ones with this issue. In case of python2, you need to install pyparsing 1.5.7 that is compliant with Python 2.7, whereas pyparsing 2.0 is compliant with Python 3.0

You can do that from the command line with the following command:

sudo pip install pyparsing==1.5.7

Sources:

https://github.com/matplotlib/matplotlib/issues/1792/
https://www.odoo.com/forum/help-1/question/installation-issue-pyparsing-2-0-0-6876

**Comment by Fran008** [comment]
You are right, if I install with command

pip2 install cloudscraper

then it installs the right way with no errors.

The problem comes if I do the install with

sudo git clone https://github.com/VeNoMouS/cloudscraper
cd cloudscraper
sudo python setup.py install

In the second case, it raises the pyparsing error, due to the explanation given in the last post.
