### ISSUE TITLE
Cannot import name 'CloudflareLoopProtection'

### ISSUE THREAD

**Issue by NinoSoles** [VeNoMouS/cloudscraper#221]
Im trying to run my script on a linux server and im getting the following error:

```
Traceback (most recent call last):
  File "Raffle_Bot_Slack.py", line 2, in <module>
    import cloudscraper
  File "/home/boltx3/.local/lib/python3.6/site-packages/cloudscraper/__init__.py", line 27, in <module>
    from .exceptions import (
ImportError: cannot import name 'CloudflareLoopProtection'
```
heres what I get when I run pip3 show cloudscraper

```
Name: cloudscraper
Version: 1.2.38
Summary: A Python module to bypass Cloudflare's anti-bot page.
Home-page: https://github.com/venomous/cloudscraper
Author: VeNoMouS
Author-email: venom@gen-x.co.nz
License: UNKNOWN
Location: /home/boltx3/.local/lib/python3.6/site-packages
Requires: requests, requests-toolbelt, pyparsing
```

**Comment by NinoSoles** [comment]
Fixed it by uninstalling then installing again
