### ISSUE TITLE
Bypass reCaptcha / hCaptcha

### ISSUE THREAD

**Issue by Danny1994d** [VeNoMouS/cloudscraper#227]
Summary.

## Expected Result

Hello, how can bypass hcaptcha ? im testing but nothing
get error 

tested with recaptcha and hcaptcha

## Actual Result

File "/usr/local/lib/python3.5/dist-packages/cloudscraper/__init__.py", line 128, in __init__
    super(CloudScraper, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'hCaptcha'

for recaptcha just get  
ERROR:root:Unable to load 2captcha anti reCaptcha provider

## Reproduction Steps 

```python
import cloudscraper

def bypass():
	pprr = open(list).readlines()
	proxy = random.choice(pprr).strip().split(":")
	scraper = cloudscraper.create_scraper(
  interpreter='nodejs',
  hCaptcha={
    'provider': '2captcha',
    'api_key': 'key'
  }
)

	scraper.proxies = {}

```

## System Information

    $ python -m cloudscraper.help

```python
{
    "platform": {
        "system": "Linux",
        "release": "4.9.0-12-amd64"
    },
    "interpreter": {
        "name": "CPython",
        "version": "3.5.3"
    },
    "cloudscraper": "1.2.40",
    "requests": "2.23.0",
    "urllib3": "1.24.3",
    "OpenSSL": {
        "version": "OpenSSL 1.1.1  11 Sep 2018",
        "ciphers": "get_ciphers() is unsupported"
    }
}

```

## Debug Log
- Add `debug=True` to `create_scraper()`

```
<paste_here>
```

This command is only available on cloudscraper v1.2.33 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system).

**Comment by VeNoMouS** [comment]
```
hCaptcha={
    'provider': '2captcha',
    'api_key': 'key'
  }```

**recaptcha**

**Comment by Danny1994d** [comment]
> ```
> hCaptcha={
>     'provider': '2captcha',
>     'api_key': 'key'
>   }
> ```
> 
> **recaptcha**

why get  ERROR:root:Unable to load 2captcha anti reCaptcha provider
we have installed  pip3 install anticaptcha, twocaptchaapi, also for nodejs

**Comment by VeNoMouS** [comment]
You can test via loading the module directly...

Example of it loading correct...

```python
>>> import cloudscraper
>>> cloudscraper.reCaptcha.dynamicImport('2captcha')
<cloudscraper.reCaptcha.2captcha.captchaSolver object at 0x7f7a67ca53c8>
>>>
```

Example if you miss-spell the provider..

```python
>>> cloudscraper.reCaptcha.dynamicImport('antipcaptcha')
ERROR:root:Unable to load antipcaptcha anti reCaptcha provider
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/cloudscraper/reCaptcha/__init__.py", line 28, in dynamicImport
    __import__('{}.{}'.format(cls.__module__, name))
ModuleNotFoundError: No module named 'cloudscraper.reCaptcha.antipcaptcha'
```

Example... if you don't have the right packages installed...
```python
>>> cloudscraper.reCaptcha.dynamicImport('anticaptcha')
ERROR:root:Unable to load anticaptcha anti reCaptcha provider
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/cloudscraper/reCaptcha/__init__.py", line 28, in dynamicImport
    __import__('{}.{}'.format(cls.__module__, name))
  File "/usr/local/lib/python3.7/dist-packages/cloudscraper/reCaptcha/anticaptcha.py", line 75, in <module>
    captchaSolver()
  File "/usr/local/lib/python3.7/dist-packages/cloudscraper/reCaptcha/anticaptcha.py", line 31, in __init__
    "Please upgrade the python module 'python_anticaptcha' via "
ImportError: Please upgrade the python module 'python_anticaptcha' via pip install -U python-anticaptcha or https://github.com/ad-m/python-anticaptcha/
>>>
```
