### ISSUE TITLE
Works great on websites protected by cloudlflare but if I try to run multiple threads, errors occur

### ISSUE THREAD

**Issue by hobocow** [VeNoMouS/cloudscraper#75]
Hi Venomous,

I'm trying to make requests to a website protected by cloudflare, my python code works fine with cloudscraper and I can access the website.

But if I try to make multiple requests at the same time with the threading module, 50%-80% of the threads would get : 

### ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.

```
PyJs_LONG_0_
ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cloudscraper/__init__.py", line 216, in sendChallengeResponse
    ('jschl_answer', JavaScriptInterpreter.dynamicImport(self.interpreter).solveChallenge(body, domain))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cloudscraper/interpreters/__init__.py", line 81, in solveChallenge
    js
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cloudscraper/interpreters/js2py.py", line 27, in eval
    result = context.eval('{}{}'.format(jsEnv, js))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/evaljs.py", line 204, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/evaljs.py", line 199, in execute
    exec (compiled, self._context)
  File "<EvalJS snippet>", line 4, in <module>
  File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1463, in call
    return Js(self.code(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/host/jseval.py", line 45, in Eval
    executor(py_code)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/host/jseval.py", line 51, in executor
    exec (code, globals())
  File "<string>", line 89, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/js2py/base.py", line 1157, in get
    raise MakeError('ReferenceError', '%s is not defined' % prop)
js2py.internals.simplex.JsException: ReferenceError: xZoHucH is not defined
```

### During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 157, in test
    req = s.post(url,headers=post_headers,data=signup_data,proxies=proxies)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cloudscraper/__init__.py", line 141, in request
    self.request('GET', resp.url, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cloudscraper/__init__.py", line 145, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cloudscraper/__init__.py", line 220, in sendChallengeResponse
    raise ValueError('Unable to parse Cloudflare anti-bots page: {} {}'.format(e.message, BUG_REPORT))
AttributeError: 'JsException' object has no attribute 'message'

```

Any help is greatly appreciated !!

**Comment by hobocow** [comment]
Hi,

### Changing the java interpreter to `interpreter='nodejs'` did the trick for me !! 

Though I have another question, what will happen if the website is under heavy load and laggy and the delay is the default one ? (5s)

I'm afraid it will decrease the performance of my threads in the case where the website isn't under heavy load and I increase the delay.

Thanks

**Comment by VeNoMouS** [comment]
a) the "delay" you refer to is nothing to do with the site... it is for cloudflare to allow for data population inside their systems off their cdn nodes so when you issue an answer it can be validated centrally.
b) if your worried about the "delay"... simply issue overwrite and increase the delay with the following

```python
scraper.delay = 10
```

__or__

```python 
scraper = cloudscraper.create_scraper(delay=10)
```

**Comment by hobocow** [comment]
Hi,

Thank you for the clarification but damn you talk like such a jerk.

Have a good day sir

**Comment by VeNoMouS** [comment]
@hobocow,

even though you deleted your comment im replying to your view that you think I'm "a jerk" for my response... 

Well your entitled to think that, but I gave you a direct answer, and gave you insight how to improve your code and how to get around challenge delay on each request by loading stored session.. 

so if you think i'm "a jerk" ... all good... you're more than welcome to not use the library.... I didn't have to answer your query..

Anyway, have a nice day

- VeN
