### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'user_agent'

### ISSUE THREAD

**Issue by pun-private** [VeNoMouS/cloudscraper#93]
Hi !

I'm having trouble setting my own user agent and I tried the example your provided in the README.

```python
import subprocess
import cloudscraper
import pickle

scraper = cloudscraper.create_scraper()

ua = "Scraping Bot"
cookie_arg, user_agent = cloudscraper.get_cookie_string("http://somesite.com", user_agent=ua)
```

It answers with `TypeError: request() got an unexpected keyword argument 'user_agent'`. Here is the full stack :

```
ERROR:root:"http://somesite.com" returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "clf_cookie.py", line 9, in <module>
    cookie_arg, user_agent = cloudscraper.get_cookie_string("http://somesite.com", user_agent=ua)
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.2.14-py2.7.egg/cloudscraper/__init__.py", line 536, in get_cookie_string
    tokens, user_agent = cls.get_tokens(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.2.14-py2.7.egg/cloudscraper/__init__.py", line 500, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 515, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cloudscraper-1.2.14-py2.7.egg/cloudscraper/__init__.py", line 191, in request
    super(CloudScraper, self).request(method, url, *args, **kwargs)
TypeError: request() got an unexpected keyword argument 'user_agent'
```

Am I doing something wrong ? Thx :)

**Comment by VeNoMouS** [comment]
That is due to cloudflare expecting specific browsers etc and having specific ordering of their header.

IUAM is an __anti-bot__ feature......

**Comment by VeNoMouS** [comment]
Actually reconsidering this...

What i'll do is rewrite the user-agent class to allow a custom... but the developer will use it their risk... I will not offer any support on custom UA's.

I don't want to block other developers out from doing their own thing and feel that it's my way or the highway.

**Comment by pun-private** [comment]
Oh thx ! Using custom ua is something I need in my architecture so I appreciate it !

**Comment by VeNoMouS** [comment]
Something like this ok....

```python
>>> from lib import cloudscraper
>>> cloudscraper.get_cookie_string("https://www.evilsite.com", browser={'custom': 'scraper bot'}, debug=True)
< GET / HTTP/1.1
< Host: www.evilsite.com
< User-Agent: scraper bot
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
< Accept-Language: en-US,en;q=0.9
< Accept-Encoding: gzip, deflate, br
<

> HTTP/1.1 503 Service Temporarily Unavailable
> Date: Thu, 28 Nov 2019 21:40:25 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: close
> Set-Cookie: __cfduid=ddf334f56f9b10c563d9595f7be5f9dcb1574977225; expires=Sat, 28-Dec-19 21:40:25 GMT; path=/; domain=.evilsite.com; HttpOnly
> X-Frame-Options: SAMEORIGIN
> Cache-Control: no-cache
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 53cf800b6db0ee9a-AKL
```

```python
>>> cloudscraper.get_cookie_string("https://www.evilsite.com", browser={'custom': 'scraper bot'})
('__cfduid=d02006e557eb7fb6c1a37bd3d14d40ca11574977427; cf_clearance=8da3f198fc1d4b2513a9749106a7754a238f197b-1574977427-0-150', 'scraper bot')
>>>
```

**Comment by VeNoMouS** [comment]
@pun-private it's in the dev branch if you want to test it out...

**Comment by pun-private** [comment]
I have to take a plane, I'll try it when I'll come back :) Thx for the quick effort

**Comment by mookiegit** [comment]
Great feature, thanks a lot!

If it's not too complicated to implement, I would suggest a small enhancement:
If the provided custom user agent matches one of the configured user agents in user_agent/browsers.json, then pick the configured headers and ciphers from there. What do you think?

**Comment by VeNoMouS** [comment]
@mookiegit 8a4797186eac67a5b09b3cd418fa2032b1c235a should clear that up for you

**Comment by pun-private** [comment]
Hey ! I confirm it works :) Thank you !
